services:

    proxy-reverso:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        image: adrianoluisdasilva/proxy-reverso
        container_name: proxy-reverso
        networks:
            - rede-desafio-2
        ports:
            - "8080:8080"
        depends_on:
            - app

    app:
        build:
            context: ./node
            dockerfile: Dockerfile
        image: adrianoluisdasilva/app
        container_name: app
        networks:
            - rede-desafio-2
        tty: true
        entrypoint: dockerize -wait tcp://sgbd:3306 -timeout 30s node index.js
        volumes:
            - ./node:/usr/src/app
            - ./node:/usr/src/app/node_modules
        depends_on:
            - sgbd

    sgbd:
        build:
            context: ./mysql
            dockerfile: Dockerfile
        image: adrianoluisdasilva/sgbd
        container_name: sgbd
        volumes:
            - ./bd:/var/lib/mysql
        networks:
            - rede-desafio-2
        environment:
            - MYSQL_DATABASE=dbpeople
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=1
        restart: always
        tty: true

networks:
    rede-desafio-2:
      driver: bridge
