services:

    proxy-reverso:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: proxy-reverso
        networks:
            - rede-desafio-2
        ports:
            - "8080:8080"
        depends_on:
            - app

    app:
        build:
            context: ./node
            dockerfile: Dockerfile
        container_name: app
        networks:
            - rede-desafio-2
        tty: true
        entrypoint: dockerize -wait tcp://sgbd:3306 -timeout 30s node index.js
        volumes:
            - ./node:/usr/src/app
            - /usr/src/app/node_modules
        depends_on:
            - sgbd

    sgbd:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: sgbd
        volumes:
            - ./mysql:/var/lib/mysql
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - rede-desafio-2
        environment:
            - MYSQL_DATABASE=dbpeople
            - MYSQL_ROOT_PASSWORD=root
        restart: always
        tty: true

networks:
    rede-desafio-2:
      driver: bridge
